fix TabErrors in sample code
the sample code contained 3x TabError's where spaces were mixed with tabs causing errors like

File "C:\cygwin64\home\hans\tibia\pybot\test.py", line 25
    self.no = None
TabError: inconsistent use of tabs and spaces in indentation